INSERT INTO ROLES VALUES (1,'ADMIN');
INSERT INTO ROLES VALUES (2,'USER');
INSERT INTO USERS VALUES (1,'$2a$12$FTczDhmL2AyB1gZGSgcFh.9AJmxbb2ie9hqRS1NkwFpLkFzuo1.uu','ADMIN1');
INSERT INTO USERS VALUES (2,'$2a$12$FTczDhmL2AyB1gZGSgcFh.9AJmxbb2ie9hqRS1NkwFpLkFzuo1.uu','USER1');
INSERT INTO USER_ROLES VALUES (1,1);
INSERT INTO USER_ROLES VALUES (2,2);